### PR TITLE
Bump supported android studio version to Giraffe

### PR DESCRIPTION
**Pull request by LionZXY**

### CODE REVIEW

**Comment by code-n-roll** [comment]
@LionZXY hi, what is the estimation time of merge ?)

**Comment by LionZXY** [comment]
I don't know, the PR is ready, everything works. Question for maintainers

**Comment by code-n-roll** [comment]
@PStrelchenko or @hh-a-team ?

**Comment by PStrelchenko** [comment]
We will make it as soon as possible, this or the next week.

**Pull request closed without merging**
